# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adc_view.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dataLayout = QtWidgets.QVBoxLayout()
        self.dataLayout.setObjectName("dataLayout")
        self.ts_layout = QtWidgets.QHBoxLayout()
        self.ts_layout.setObjectName("ts_layout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.ts_layout.addWidget(self.label_2)
        self.channelsSelector = QtWidgets.QComboBox(self.centralwidget)
        self.channelsSelector.setObjectName("channelsSelector")
        self.ts_layout.addWidget(self.channelsSelector)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ts_layout.addWidget(self.line_2)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.ts_layout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setObjectName("stopButton")
        self.ts_layout.addWidget(self.stopButton)
        self.stopOnErrorCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.stopOnErrorCheckBox.setObjectName("stopOnErrorCheckBox")
        self.ts_layout.addWidget(self.stopOnErrorCheckBox)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ts_layout.addWidget(self.line_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.ts_layout.addWidget(self.label)
        self.rateComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.rateComboBox.setObjectName("rateComboBox")
        self.ts_layout.addWidget(self.rateComboBox)
        self.dataLayout.addLayout(self.ts_layout)
        self.divider = QtWidgets.QFrame(self.centralwidget)
        self.divider.setFrameShape(QtWidgets.QFrame.HLine)
        self.divider.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.divider.setObjectName("divider")
        self.dataLayout.addWidget(self.divider)
        self.plotFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotFrame.sizePolicy().hasHeightForWidth())
        self.plotFrame.setSizePolicy(sizePolicy)
        self.plotFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.dataLayout.addWidget(self.plotFrame)
        self.horizontalLayout.addLayout(self.dataLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(34)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.statsLayout = QtWidgets.QVBoxLayout()
        self.statsLayout.setObjectName("statsLayout")
        self.statsLabel = QtWidgets.QLabel(self.centralwidget)
        self.statsLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statsLabel.setFont(font)
        self.statsLabel.setObjectName("statsLabel")
        self.statsLayout.addWidget(self.statsLabel)
        self.statsTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statsTable.sizePolicy().hasHeightForWidth())
        self.statsTable.setSizePolicy(sizePolicy)
        self.statsTable.setMinimumSize(QtCore.QSize(300, 0))
        self.statsTable.setMaximumSize(QtCore.QSize(300, 16777215))
        self.statsTable.setObjectName("statsTable")
        self.statsTable.setColumnCount(0)
        self.statsTable.setRowCount(0)
        self.statsLayout.addWidget(self.statsTable)
        self.horizontalLayout.addLayout(self.statsLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADC Viewer"))
        self.label_2.setText(_translate("MainWindow", "ADC channels"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.stopOnErrorCheckBox.setText(_translate("MainWindow", "Stop on error"))
        self.label.setText(_translate("MainWindow", "Max update rate"))
        self.statsLabel.setText(_translate("MainWindow", "Packet information"))

