# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_source.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dataSourceDialog(object):
    def setupUi(self, dataSourceDialog):
        dataSourceDialog.setObjectName("dataSourceDialog")
        dataSourceDialog.resize(643, 186)
        self.gridLayout = QtWidgets.QGridLayout(dataSourceDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(dataSourceDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pcapReadout = QtWidgets.QVBoxLayout()
        self.pcapReadout.setObjectName("pcapReadout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pcapReadout.addItem(spacerItem)
        self.openPcapButton = QtWidgets.QPushButton(self.widget)
        self.openPcapButton.setObjectName("openPcapButton")
        self.pcapReadout.addWidget(self.openPcapButton)
        self.horizontalLayout.addLayout(self.pcapReadout)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pythonReadout = QtWidgets.QVBoxLayout()
        self.pythonReadout.setObjectName("pythonReadout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.pythonReadout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pythonReadout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pySocketLabel = QtWidgets.QLabel(self.widget)
        self.pySocketLabel.setObjectName("pySocketLabel")
        self.horizontalLayout_2.addWidget(self.pySocketLabel)
        self.pySocket = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pySocket.sizePolicy().hasHeightForWidth())
        self.pySocket.setSizePolicy(sizePolicy)
        self.pySocket.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pySocket.setObjectName("pySocket")
        self.horizontalLayout_2.addWidget(self.pySocket)
        self.pythonReadout.addLayout(self.horizontalLayout_2)
        self.pythonInterpButton = QtWidgets.QPushButton(self.widget)
        self.pythonInterpButton.setObjectName("pythonInterpButton")
        self.pythonReadout.addWidget(self.pythonInterpButton)
        self.horizontalLayout.addLayout(self.pythonReadout)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.cppReadout = QtWidgets.QVBoxLayout()
        self.cppReadout.setObjectName("cppReadout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.cppReadout.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.cppReadout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cppSocketLabel = QtWidgets.QLabel(self.widget)
        self.cppSocketLabel.setObjectName("cppSocketLabel")
        self.horizontalLayout_3.addWidget(self.cppSocketLabel)
        self.cppSocket = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cppSocket.sizePolicy().hasHeightForWidth())
        self.cppSocket.setSizePolicy(sizePolicy)
        self.cppSocket.setMaximumSize(QtCore.QSize(70, 16777215))
        self.cppSocket.setObjectName("cppSocket")
        self.horizontalLayout_3.addWidget(self.cppSocket)
        self.cppReadout.addLayout(self.horizontalLayout_3)
        self.cppInterpButton = QtWidgets.QPushButton(self.widget)
        self.cppInterpButton.setObjectName("cppInterpButton")
        self.cppReadout.addWidget(self.cppInterpButton)
        self.horizontalLayout.addLayout(self.cppReadout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(dataSourceDialog)
        QtCore.QMetaObject.connectSlotsByName(dataSourceDialog)

    def retranslateUi(self, dataSourceDialog):
        _translate = QtCore.QCoreApplication.translate
        dataSourceDialog.setWindowTitle(_translate("dataSourceDialog", "Select data source"))
        self.openPcapButton.setText(_translate("dataSourceDialog", "Open PCAP file"))
        self.label.setText(_translate("dataSourceDialog", "Python based data reader"))
        self.pySocketLabel.setText(_translate("dataSourceDialog", "Socket"))
        self.pySocket.setText(_translate("dataSourceDialog", "65535"))
        self.pythonInterpButton.setText(_translate("dataSourceDialog", "Open UDP stream"))
        self.label_2.setText(_translate("dataSourceDialog", "C++ based reader"))
        self.cppSocketLabel.setText(_translate("dataSourceDialog", "Socket"))
        self.cppSocket.setText(_translate("dataSourceDialog", "65535"))
        self.cppInterpButton.setText(_translate("dataSourceDialog", "Open UDP stream"))

